language: ruby
rvm:
  - 2.6.3

install: chmod +x script/bootstrap
script: chmod +x script/cibuild

branches:
  only:
  - main     
  - gh-pages # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

cache:
  bundler: true # caching bundler gem packages will speed up build
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

exclude: [vendor]

sudo: false # route your build to the container-based infrastructure for a faster build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
