# Settings
title: "Data Journey"
author: Mervyn
description: "Blog on C S"
show_downloads: true
google_analytics:
remote_theme: pages-themes/hacker

# Where things are
source              : .
destination         : ./_site
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layout
data_dir            : _data
includes_dir        : _includes
sass :
  sass_dir: _sass
  sourcemap: never
collections :
  posts :
    output          : true

# Handling Reading
safe                : false
include             :
  - .htaccess
exclude             :
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .jekyll-cache
  - vendor

keep_files          :
  - .git
  - .svn
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           :
  - jekyll-feed
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
plugins             :
  - jekyll-feed
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Serving
url: https://jwmc999.github.io
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : /:categories/:title/
paginate_path       : /page:num/
timezone            : null

quiet               : false
verbose             : false
defaults            :
  # _posts
  - scope:
      path: ""      
      type: posts
    values:
      layout: post

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  input             : GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
       css_class: 'highlight'
