# Settings
title: "Data Journey"
description: "Blog on C S"
show_downloads: true
google_analytics: 
theme: hacker

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
