# Site
title: Data Journey
description: Blog on C S
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
## Introduction
* Prologue
### Journey Codes
* Stage 0. Pack Up!
* Data Structure (DS)
* C Language (C)
* Discrete Mathematics (M)
* Extra Curriculum (Ex)

# Author
author:
 sal: Jaewon Mervyn Chung
 display_name: MERVYN
 gravatar: 
 email: rskessy@gmail.com
 web: https://Jwmc999.github.io
 linkedin: https://linkedin.com/in/mervyn-chung/
 description: "Student"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
