on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: build
        run: script/bootstrap
      - name: make script/bootstrap executable
        run: chmod +x script/bootstrap
      - name: test
        run: script/cibuild
